apiVersion: v1
kind: Pod
metadata:
  name: snap
  namespace: kube-system
spec:
  hostPID: true
  hostNetwork: true
  containers:
  - name: snap
    image: 10.1.23.1:5000/snap:1
    args: ["--tribe"]
    volumeMounts:
      - mountPath: /sys/fs/cgroup
        name: cgroup
      - mountPath: /var/run/docker.sock
        name: docker-sock
    ports:
    - containerPort: 8181
      hostPort: 8181
      name: snap-api
    imagePullPolicy: Always
  nodeSelector:
    tribe-role: chief
  volumes:
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
